### PR TITLE
Fix issue from dry run

### LINKED ISSUE #108: Deleting multiple items through remove will require typing the password multiple times
If I am deleting multiple Loans through the `remove` command, it would be better if I only had to type in the password for the first remove command, then subsequent commands follow the verification that I had already done and do not require verification.

### LINKED ISSUE #173: Passwords should be hidden when viewing through command history
Otherwise, the system is easily vulnerable (i.e. if I enter a command that uses the password, such as setpass or remind, then enter history or use the up key, I can view the passwords previously entered, which poses a simple attack vector).

Steps to reproduce:
1) Use the setpass command (i.e. setpass a12345 b12345)
2) Type history or press the up key

The passwords originally entered are easily visible in the command result box or in the command field.

### LINKED ISSUE #201: [PE Dry Run]IC format errors in 'Add' Command
It is stated that the ic/ paramete could be left blank, however I could not get this to succeed. 

I tried 
- removing the prefix
ic-noprefix
- leaving the prefix with no parameter
ic-noparam
- adding a space after the prefix.
ic-space

It could be more clear as to what "It may be blank" means.

<hr>

**Reported by:** @snookerballs
**Severity:** `Medium`

<sub>[original: nus-cs2103-AY1819S1/pe-dry-run#357]</sub>

### LINKED ISSUE #202: [PE Dry Run]Insecure password input in `delete` command
Input of password should be separate from the command arguments since it is sensitive data

<hr>

**Reported by:** @indocomsoft
**Severity:** `High`

<sub>[original: nus-cs2103-AY1819S1/pe-dry-run#361]</sub>

### LINKED ISSUE #208: [PE Dry Run]Wrong error message for invalid date
When using command `search 2018-01-01 2018-11-31`, the error was `Dates provided are in an invalid format. Please use the format YYYY-MM-DD.`. However, the format is correct, it's just that the date itself that's invalid

<hr>

**Reported by:** @indocomsoft
**Severity:** `Medium`

<sub>[original: nus-cs2103-AY1819S1/pe-dry-run#474]</sub>

### LINKED ISSUE #225: [PE Dry Run]Regarding password
cannot figure out what my default password is. Also, if the user forget her password, there seems to be no way to figure out the old password.

<hr>

**Reported by:** @barkhyehyeon
**Severity:** `Medium`

<sub>[original: nus-cs2103-AY1819S1/pe-dry-run#785]</sub>

### PR DESCRIPTION
**Pull request by wn96**
Fixes the following issues:

Fix #208 
Fix #201 

Documentation to fix following issue by v2.0
- Fix #225 
- Fix #202 
- Fix #108 
- Fix #173

### CODE REVIEW

File: src/main/java/loanbook/model/loan/Nric.java [hunk 1]
```diff
@@ -9,7 +9,7 @@
 public class Nric implements Censor {
 
     public static final String MESSAGE_NRIC_CONSTRAINTS =
-            "NRIC should be Singapore issued. It may be blank. ";
+            "Invalid NRIC input. NRIC should consist of a prefix letter, followed by 7 letters and a checksum suffix.";
```
Comment (xantho09) [inline src/main/java/loanbook/model/loan/Nric.java]: I think by taking away the "NRIC should be Singapore issued" message, users might be confused why "S0000000A" isn't working since, as far as they're concerned, it matches the format specified. (They might not know what a "checksum suffix" is, or how it works)

Though, I'm not sure what a suitable replacement should be... 

Perhaps just "Invalid NRIC input. It should be a valid Singapore-issued NRIC number", or something.

Comment (wn96) [reply src/main/java/loanbook/model/loan/Nric.java]: Resolved!
